# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import logging
import typing
import v8
from typing import TypeAlias
__all__ = [
    "Atomics",
    "Console",
    "DynamicCodePolicy",
    "HostAPI",
    "Inspector",
    "MicrotaskQueue",
    "ModuleLoader",
    "PromiseRejectionTracker",
    "ShadowRealm",
    "SharedArrayBuffer",
    "Timer",
    "WebAssembly",
]

_WebAssemblyLoaderLike: TypeAlias = collections.abc.Mapping[str, bytes] | collections.abc.Callable[[str], bytes]
r"""
Python WebAssembly streaming loader accepted by v8.api.WebAssembly.
"""

@typing.final
class Atomics(HostAPI):
    r"""
    Configures V8 Atomics support, including whether blocking waits are allowed.
    """
    @property
    def allow_wait(self) -> builtins.bool:
        r"""
        Return whether Atomics.wait is allowed to block.
        """
    def __new__(cls, allow_wait: builtins.bool = True) -> Atomics:
        r"""
        Create an Atomics HostAPI configuration.
        """

@typing.final
class Console(HostAPI):
    r"""
    Installs console methods that forward to a Python logging.Logger.
    """
    @property
    def logger(self) -> logging.Logger:
        r"""
        Return the Python logger used by installed console methods.
        """
    def __new__(cls, logger: logging.Logger | None = None, *, name: builtins.str = 'v8.console') -> Console:
        r"""
        Create a console HostAPI backed by a Python logger.
        """

@typing.final
class DynamicCodePolicy(HostAPI):
    r"""
    Controls whether dynamic JavaScript code generation is allowed.
    """
    @property
    def allow_eval(self) -> builtins.bool:
        r"""
        Return whether eval and Function-style dynamic code generation are allowed.
        """
    def __new__(cls, allow_eval: builtins.bool = False) -> DynamicCodePolicy:
        r"""
        Create a dynamic code policy HostAPI.
        """

class HostAPI:
    r"""
    Base class for host-side APIs that can be installed into a BaseProfile.
    """
    ...

@typing.final
class Inspector(HostAPI):
    r"""
    Installs V8 Inspector support for a context.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Return the inspector context name.
        """
    @property
    def context_group_id(self) -> builtins.int:
        r"""
        Return the inspector context group id.
        """
    @property
    def aux_data(self) -> typing.Optional[builtins.str]:
        r"""
        Return auxiliary inspector context data.
        """
    def __new__(cls, name: builtins.str = 'v8-python', *, context_group_id: builtins.int = 1, aux_data: typing.Optional[builtins.str] = None) -> Inspector:
        r"""
        Create an Inspector HostAPI configuration.
        """

@typing.final
class MicrotaskQueue(HostAPI):
    r"""
    Installs queueMicrotask into the JavaScript global object.
    """
    def __new__(cls) -> MicrotaskQueue:
        r"""
        Create a HostAPI that installs queueMicrotask.
        """

@typing.final
class ModuleLoader(HostAPI):
    r"""
    Installs host-backed static and dynamic ECMAScript module resolution.
    """
    def __new__(cls, resolver: collections.abc.Mapping[str, str | v8.Module] | collections.abc.Callable[[str, str | None, dict[str, str]], str | v8.Module | None] | None = None, *, import_meta: collections.abc.Mapping[str, object] | collections.abc.Callable[[str], collections.abc.Mapping[str, object] | None] | None = None) -> ModuleLoader:
        r"""
        Create a module loader from a mapping or resolver callback.
        """

@typing.final
class PromiseRejectionTracker(HostAPI):
    r"""
    Installs V8 promise rejection tracking with an optional Python callback.
    """
    def __new__(cls, policy: typing.Literal['ignore', 'warn'] = "warn", *, callback: collections.abc.Callable[[str, str | None], object] | None = None) -> PromiseRejectionTracker:
        r"""
        Create a promise rejection tracker HostAPI.
        """

@typing.final
class ShadowRealm(HostAPI):
    r"""
    Enables V8's ShadowRealm support for contexts that install this HostAPI.
    """
    def __new__(cls) -> ShadowRealm:
        r"""
        Create a HostAPI that enables and installs ShadowRealm support.
        """

@typing.final
class SharedArrayBuffer(HostAPI):
    r"""
    Enables SharedArrayBuffer construction in contexts that install this HostAPI.
    """
    def __new__(cls) -> SharedArrayBuffer:
        r"""
        Create a HostAPI that installs the SharedArrayBuffer constructor.
        """

@typing.final
class Timer(HostAPI):
    r"""
    Installs browser-style timer globals backed by the Rust host task queue.
    """
    def __new__(cls) -> Timer:
        r"""
        Create a timer HostAPI that installs setTimeout, clearTimeout, setInterval, and clearInterval.
        """

@typing.final
class WebAssembly(HostAPI):
    r"""
    Installs WebAssembly streaming helpers and configures Wasm code generation.
    """
    @property
    def allow_code_generation(self) -> builtins.bool:
        r"""
        Return whether WebAssembly code generation is allowed.
        """
    @property
    def loader(self) -> _WebAssemblyLoaderLike | None:
        r"""
        Return the Python streaming loader, if one was configured.
        """
    @property
    def cache(self) -> v8.WasmModuleCache | None:
        r"""
        Return the optional compiled Wasm module cache.
        """
    def __new__(cls, loader: _WebAssemblyLoaderLike | None = None, *, allow_code_generation: builtins.bool = True, cache: v8.WasmModuleCache | None = None) -> WebAssembly:
        r"""
        Create a WebAssembly HostAPI configuration.
        """

