# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import datetime
import typing
from typing import TypeAlias
from . import api
__all__ = [
    "Array",
    "ArrayBuffer",
    "ArrayBufferView",
    "BaseProfile",
    "BigInt",
    "CompiledWasmModule",
    "Context",
    "ContextBuilder",
    "DataView",
    "Date",
    "External",
    "Function",
    "Inspector",
    "InspectorSession",
    "Isolate",
    "JavaScriptError",
    "Map",
    "Message",
    "Module",
    "Object",
    "Private",
    "Promise",
    "PropertyAttribute",
    "PropertyDescriptor",
    "Proxy",
    "RegExp",
    "Scope",
    "Script",
    "Set",
    "SnapshotCreator",
    "StackFrame",
    "StackTrace",
    "StartupData",
    "String",
    "Symbol",
    "TypedArray",
    "Value",
    "WasmModule",
    "WasmModuleCache",
    "api",
    "cached_data_version_tag",
    "collect_garbage",
]

_HostCallable: TypeAlias = collections.abc.Callable[..., object]
r"""
Python callable that can be exposed to JavaScript.
"""

_HostClassDecorator: TypeAlias = collections.abc.Callable[[_HostClassLike], _HostClassLike]
r"""
Decorator returned by class_ when no class is supplied.
"""

_HostClassLike: TypeAlias = type[object]
r"""
Python class that can be exposed as a JavaScript constructor template.
"""

_HostFunctionDecorator: TypeAlias = collections.abc.Callable[[_HostCallable], _HostCallable]
r"""
Decorator returned by host_function when no callable is supplied.
"""

_JSAccessorLike: TypeAlias = Function | Value
r"""
JavaScript function value accepted as an accessor getter or setter.
"""

_JSArrayLike: TypeAlias = list[object] | tuple[object, ...]
r"""
Python sequence containers converted to JavaScript arrays.
"""

_JSBytesLike: TypeAlias = bytes | bytearray | memoryview[int]
r"""
Python bytes-like objects accepted by V8 conversion APIs.
"""

_JSFunctionArgsLike: TypeAlias = list[_JSValueLike] | tuple[_JSValueLike, ...]
r"""
Positional JavaScript call arguments.
"""

_JSObjectLike: TypeAlias = dict[object, object]
r"""
Python mapping container converted to a JavaScript object.
"""

_JSPropertyNameLike: TypeAlias = str | String | Symbol | Value
r"""
Values accepted where V8 requires a string or symbol property name.
"""

_JSValueLike: TypeAlias = Value | String | Object | Array | Function | Promise | BigInt | Symbol | ArrayBuffer | ArrayBufferView | TypedArray | DataView | Map | Set | Date | RegExp | Proxy | External | WasmModule | str | int | float | bool | None | _JSBytesLike | _JSArrayLike | _JSObjectLike
r"""
Python values accepted by APIs that convert inputs to JavaScript values.
"""

_ModuleImportsLike: TypeAlias = dict[str, str | Module]
r"""
Module instantiation imports keyed by module specifier.
"""

_F = typing.TypeVar("_F", bound=collections.abc.Callable[..., object])
_C = typing.TypeVar("_C", bound=type[object])

@typing.final
class Array:
    r"""
    JavaScript Array wrapper.
    """
    def to_value(self) -> Value:
        r"""
        Return this array as a generic V8 Value.
        """
    def length(self) -> builtins.int:
        r"""
        Return the array length.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the array length.
        """
    def get(self, index: builtins.int) -> Value:
        r"""
        Read an array element.
        """
    def __getitem__(self, index: builtins.int) -> Value:
        r"""
        Read an array element.
        """
    def set(self, index: builtins.int, value: _JSValueLike) -> builtins.bool:
        r"""
        Set an array element.
        """
    def __setitem__(self, index: builtins.int, value: _JSValueLike) -> None:
        r"""
        Set an array element.
        """

@typing.final
class ArrayBuffer:
    r"""
    JavaScript ArrayBuffer wrapper.
    """
    @property
    def byte_length(self) -> builtins.int:
        r"""
        Return the byte length.
        """
    def to_value(self) -> Value:
        r"""
        Return this ArrayBuffer as a generic V8 Value.
        """
    def is_detachable(self) -> builtins.bool:
        r"""
        Return whether this ArrayBuffer can be detached.
        """
    def was_detached(self) -> builtins.bool:
        r"""
        Return whether this ArrayBuffer has been detached.
        """
    def detach(self) -> builtins.bool:
        r"""
        Detach this ArrayBuffer.
        """
    def to_bytes(self) -> bytes:
        r"""
        Copy this ArrayBuffer into Python bytes.
        """
    def copy_contents(self) -> bytes:
        r"""
        Copy this ArrayBuffer into Python bytes.
        """
    def memoryview(self) -> memoryview:
        r"""
        Return a Python memoryview over copied bytes.
        """
    def __bytes__(self) -> bytes:
        r"""
        Return this ArrayBuffer as Python bytes.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the byte length.
        """
    def typed_array(self, kind: builtins.str = 'Uint8Array', byte_offset: builtins.int = 0, length: typing.Optional[builtins.int] = None) -> TypedArray:
        r"""
        Create a TypedArray view over this ArrayBuffer.
        """
    def as_uint8_array(self, byte_offset: builtins.int = 0, length: typing.Optional[builtins.int] = None) -> TypedArray:
        r"""
        Create a Uint8Array view over this ArrayBuffer.
        """
    def data_view(self, byte_offset: builtins.int = 0, byte_length: typing.Optional[builtins.int] = None) -> DataView:
        r"""
        Create a DataView over this ArrayBuffer.
        """

@typing.final
class ArrayBufferView:
    r"""
    JavaScript ArrayBufferView wrapper.
    """
    @property
    def byte_length(self) -> builtins.int:
        r"""
        Return the view byte length.
        """
    @property
    def byte_offset(self) -> builtins.int:
        r"""
        Return the byte offset into the backing ArrayBuffer.
        """
    def to_value(self) -> Value:
        r"""
        Return this view as a generic V8 Value.
        """
    def buffer(self) -> ArrayBuffer:
        r"""
        Return the backing ArrayBuffer.
        """
    def has_buffer(self) -> builtins.bool:
        r"""
        Return whether this view has a backing buffer.
        """
    def to_bytes(self) -> bytes:
        r"""
        Copy this view into Python bytes.
        """
    def copy_contents(self) -> bytes:
        r"""
        Copy this view into Python bytes.
        """
    def memoryview(self) -> memoryview:
        r"""
        Return a Python memoryview over copied bytes.
        """
    def __bytes__(self) -> bytes:
        r"""
        Return this view as Python bytes.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the view byte length.
        """

class BaseProfile:
    r"""
    Reusable collection of host functions, host classes, and HostAPI installers.
    """
    def __new__(cls) -> BaseProfile:
        r"""
        Create an empty profile.
        """
    @typing.overload
    def host_function(self, function: _F, *, name: typing.Optional[builtins.str] = None) -> _F:
        r"""
        Register a Python callable as a JavaScript global function.
        
        Can be used directly or as a decorator. When `name` is omitted, the
        callable's `__name__` is used as the JavaScript global name.
        """
    @typing.overload
    def host_function(self, function: None = None, *, name: typing.Optional[builtins.str] = None) -> collections.abc.Callable[[_F], _F]:
        r"""
        Register a Python callable as a JavaScript global function.
        
        Can be used directly or as a decorator. When `name` is omitted, the
        callable's `__name__` is used as the JavaScript global name.
        """
    @typing.overload
    def class_(self, cls: _C, *, name: typing.Optional[builtins.str] = None) -> _C:
        r"""
        Register a Python class as a JavaScript constructor template.
        
        Can be used directly or as a decorator. Methods and properties visible
        on the Python class are exposed through V8 object templates.
        """
    @typing.overload
    def class_(self, cls: None = None, *, name: typing.Optional[builtins.str] = None) -> collections.abc.Callable[[_C], _C]:
        r"""
        Register a Python class as a JavaScript constructor template.
        
        Can be used directly or as a decorator. Methods and properties visible
        on the Python class are exposed through V8 object templates.
        """
    def host_function_count(self) -> builtins.int:
        r"""
        Return the number of registered host functions.
        """
    def class_count(self) -> builtins.int:
        r"""
        Return the number of registered host classes.
        """
    def install(self, apis: collections.abc.Iterable[api.HostAPI]) -> BaseProfile:
        r"""
        Install HostAPI instances into this profile and return the profile.
        """

@typing.final
class BigInt:
    r"""
    JavaScript BigInt wrapper.
    """
    def to_value(self) -> Value:
        r"""
        Return this BigInt as a generic V8 Value.
        """
    def as_i64(self) -> typing.Optional[builtins.int]:
        r"""
        Return this BigInt as i64 when the conversion is lossless.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return the decimal string representation.
        """
    def __int__(self) -> int:
        r"""
        Convert this BigInt to a Python int.
        """

@typing.final
class CompiledWasmModule:
    r"""
    Reusable compiled WebAssembly module handle.
    """
    @property
    def wire_bytes(self) -> bytes:
        r"""
        Return this compiled module's wire bytes.
        """
    @property
    def byte_length(self) -> builtins.int:
        r"""
        Return this compiled module's wire byte length.
        """
    @property
    def source_url(self) -> builtins.str:
        r"""
        Return this compiled module's source URL metadata.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class Context:
    r"""
    A V8 execution context tied to one isolate.
    """
    def is_alive(self) -> builtins.bool:
        r"""
        Return whether this context still owns a live V8 context and isolate.
        """
    def inspector(self) -> Inspector:
        r"""
        Return the inspector object installed for this context.
        """
    def heap_statistics(self) -> dict[str, int | bool]:
        r"""
        Return V8 heap statistics for this context's isolate.
        """
    def heap_space_statistics(self) -> list[dict[str, int | str]]:
        r"""
        Return per-space V8 heap statistics for this context's isolate.
        """
    def heap_code_statistics(self) -> dict[str, int]:
        r"""
        Return V8 heap statistics for generated code and metadata.
        """
    def low_memory_notification(self) -> None:
        r"""
        Notify V8 that the host is under low-memory pressure.
        """
    def memory_pressure(self, level: typing.Literal['none', 'moderate', 'critical']) -> None:
        r"""
        Set V8's memory pressure level for this context's isolate.
        """
    def request_garbage_collection_for_testing(self, collection_type: typing.Literal['full', 'minor'] = "full") -> None:
        r"""
        Request a V8 garbage collection cycle for testing.
        """
    def new_string(self, value: builtins.str) -> String:
        r"""
        Create a V8 string in this context.
        """
    def new_private(self, name: str | String | None = None, *, for_api: builtins.bool = False) -> Private:
        r"""
        Create a V8 private key, optionally using the API-visible key namespace.
        """
    def private_for_api(self, name: str | String | None = None) -> Private:
        r"""
        Create or retrieve a V8 API private key.
        """
    def new_object(self, internal_field_count: builtins.int = 0) -> Object:
        r"""
        Create a new V8 object, optionally with internal fields.
        """
    def new_external(self, payload: object) -> External:
        r"""
        Create a V8 external value that owns a Python payload.
        """
    def compile_wasm_module(self, wire_bytes: bytes | bytearray | memoryview, cache: typing.Optional[WasmModuleCache] = None) -> WasmModule:
        r"""
        Compile a WebAssembly module from wire bytes.
        """
    def wasm_module_from_compiled(self, compiled: CompiledWasmModule) -> WasmModule:
        r"""
        Recreate a WebAssembly module object from a compiled module handle.
        """
    def new_array_buffer(self, value: int | bytes | bytearray | memoryview) -> ArrayBuffer:
        r"""
        Create an ArrayBuffer from a byte length or bytes-like object.
        """
    def from_python(self, value: _JSValueLike) -> Value:
        r"""
        Convert a Python object into a JavaScript value in this context.
        """
    def eval(self, source: builtins.str, timeout_ms: typing.Optional[builtins.int] = None) -> Value:
        r"""
        Compile and run JavaScript source immediately.
        """
    def set_global(self, name: builtins.str, value: _JSValueLike) -> builtins.bool:
        r"""
        Set a global property on this context.
        """
    def get_global(self, name: builtins.str) -> Value:
        r"""
        Read a global property from this context.
        """
    def parse_json(self, source: builtins.str) -> Value:
        r"""
        Parse JSON source into a JavaScript value.
        """
    def serialize(self, value: _JSValueLike) -> bytes:
        r"""
        Serialize a JavaScript-compatible value using V8's structured clone format.
        """
    def deserialize(self, data: bytes | bytearray | memoryview) -> Value:
        r"""
        Deserialize bytes produced by serialize into a JavaScript value.
        """
    def perform_microtask_checkpoint(self) -> None:
        r"""
        Run V8's microtask checkpoint for this isolate.
        """
    def run_event_loop_once(self, timeout_ms: typing.Optional[builtins.int] = None) -> builtins.bool:
        r"""
        Run at most one queued host task or timer.
        """
    def run_until_idle(self, max_tasks: typing.Optional[builtins.int] = None) -> builtins.int:
        r"""
        Run queued host tasks until the queue is idle or max_tasks is reached.
        """
    def set_microtasks_policy(self, policy: builtins.str) -> None:
        r"""
        Set the microtask policy to "auto" or "explicit" for this context's isolate.
        """
    def terminate_execution(self) -> builtins.bool:
        r"""
        Request termination of currently running JavaScript execution.
        """
    def cancel_terminate_execution(self) -> builtins.bool:
        r"""
        Cancel a pending termination request for JavaScript execution.
        """
    def compile_module(self, source: builtins.str, specifier: builtins.str = '<module>') -> Module:
        r"""
        Compile an ECMAScript module with the given specifier.
        """
    def compile_function(self, source: str | String, arguments: collections.abc.Sequence[str] | None = None, *, filename: builtins.str = '<function>', source_map_url: typing.Optional[builtins.str] = None, cached_data: bytes | bytearray | memoryview | None = None) -> Function:
        r"""
        Compile JavaScript source as a function object.
        """
    def compile(self, source: str | String, *, filename: builtins.str = '<script>', source_map_url: typing.Optional[builtins.str] = None, cached_data: bytes | bytearray | memoryview | None = None) -> Script:
        r"""
        Compile JavaScript source as a reusable script.
        """

@typing.final
class ContextBuilder:
    r"""
    Builder for configuring a context before it is created.
    """
    def is_alive(self) -> builtins.bool:
        r"""
        Return whether this builder can still build a context.
        """
    def set_global(self, name: builtins.str, value: _JSValueLike) -> None:
        r"""
        Queue a global value to install when the context is built.
        """
    @typing.overload
    def host_function(self, function: _F, *, name: typing.Optional[builtins.str] = None) -> _F:
        r"""
        Register a Python callable as a JavaScript global function for this context.
        """
    @typing.overload
    def host_function(self, function: None = None, *, name: typing.Optional[builtins.str] = None) -> collections.abc.Callable[[_F], _F]:
        r"""
        Register a Python callable as a JavaScript global function for this context.
        """
    @typing.overload
    def class_(self, cls: _C, *, name: typing.Optional[builtins.str] = None) -> _C:
        r"""
        Register a Python class as a JavaScript constructor template for this context.
        """
    @typing.overload
    def class_(self, cls: None = None, *, name: typing.Optional[builtins.str] = None) -> collections.abc.Callable[[_C], _C]:
        r"""
        Register a Python class as a JavaScript constructor template for this context.
        """
    def use_profile(self, profile: BaseProfile) -> None:
        r"""
        Copy host functions, host classes, and HostAPI installers from a profile.
        """
    def use_snapshot(self, index: builtins.int = 0) -> None:
        r"""
        Build the context from a snapshot context index.
        """
    def set_microtasks_policy(self, policy: builtins.str) -> None:
        r"""
        Set the microtask policy to "auto" or "explicit".
        """
    def build(self) -> Context:
        r"""
        Consume this builder and create the configured context.
        """

@typing.final
class DataView:
    r"""
    JavaScript DataView wrapper.
    """
    @property
    def byte_length(self) -> builtins.int:
        r"""
        Return the DataView byte length.
        """
    @property
    def byte_offset(self) -> builtins.int:
        r"""
        Return the byte offset into the backing ArrayBuffer.
        """
    def to_value(self) -> Value:
        r"""
        Return this DataView as a generic V8 Value.
        """
    def buffer(self) -> ArrayBuffer:
        r"""
        Return the backing ArrayBuffer.
        """
    def to_bytes(self) -> bytes:
        r"""
        Copy this DataView into Python bytes.
        """
    def copy_contents(self) -> bytes:
        r"""
        Copy this DataView into Python bytes.
        """
    def memoryview(self) -> memoryview:
        r"""
        Return a Python memoryview over copied bytes.
        """
    def __bytes__(self) -> bytes:
        r"""
        Return this DataView as Python bytes.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the DataView byte length.
        """

@typing.final
class Date:
    r"""
    JavaScript Date wrapper.
    """
    @property
    def timestamp_ms(self) -> builtins.float:
        r"""
        Return milliseconds since the Unix epoch.
        """
    def to_value(self) -> Value:
        r"""
        Return this Date as a generic V8 Value.
        """
    def value_of(self) -> builtins.float:
        r"""
        Return milliseconds since the Unix epoch.
        """
    def timestamp(self) -> builtins.float:
        r"""
        Return seconds since the Unix epoch.
        """
    def to_datetime(self) -> datetime.datetime:
        r"""
        Convert this Date to a timezone-aware Python datetime.
        """
    def __float__(self) -> builtins.float:
        r"""
        Return milliseconds since the Unix epoch.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return JavaScript's string representation for this Date.
        """

@typing.final
class External:
    r"""
    V8 External wrapper that can carry a Python-owned payload.
    """
    @property
    def id(self) -> typing.Optional[builtins.int]:
        r"""
        Return the runtime-managed payload id.
        """
    def to_value(self) -> Value:
        r"""
        Return this external as a generic V8 Value.
        """
    def is_managed(self) -> builtins.bool:
        r"""
        Return whether this external is managed by this runtime.
        """
    def payload(self) -> object:
        r"""
        Return the Python payload stored in this external.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class Function:
    r"""
    JavaScript Function wrapper.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Return the JavaScript function name.
        """
    @property
    def script_id(self) -> builtins.int:
        r"""
        Return V8's script id for this function.
        """
    @property
    def script_line_number(self) -> typing.Optional[builtins.int]:
        r"""
        Return the script line number for this function.
        """
    @property
    def script_column_number(self) -> typing.Optional[builtins.int]:
        r"""
        Return the script column number for this function.
        """
    @property
    def resource_name(self) -> typing.Optional[builtins.str]:
        r"""
        Return the function's resource name.
        """
    @property
    def source_map_url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the function's source map URL.
        """
    @property
    def cached_data_rejected(self) -> builtins.bool:
        r"""
        Return whether supplied cached data was rejected by V8.
        """
    def to_value(self) -> Value:
        r"""
        Return this function as a generic V8 Value.
        """
    def create_code_cache(self) -> bytes:
        r"""
        Create V8 code-cache bytes for this function.
        """
    def call(self, args: _JSFunctionArgsLike | None = None, this_arg: _JSValueLike | None = None) -> Value:
        r"""
        Call this JavaScript function.
        """
    def __call__(self, *args: _JSValueLike) -> Value:
        r"""
        Call this JavaScript function with positional arguments.
        """

@typing.final
class Inspector:
    r"""
    V8 Inspector endpoint for a context.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Return the inspector context name.
        """
    @property
    def context_group_id(self) -> builtins.int:
        r"""
        Return the inspector context group id.
        """
    def connect(self, state: builtins.str = '', *, trusted: builtins.bool = True, on_message: collections.abc.Callable[[str], object] | None = None) -> InspectorSession:
        r"""
        Connect a protocol session to this inspector.
        """
    def is_alive(self) -> builtins.bool:
        r"""
        Return whether this inspector still owns an active V8 inspector.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class InspectorSession:
    r"""
    Connected V8 Inspector protocol session.
    """
    @property
    def messages(self) -> builtins.list[builtins.str]:
        r"""
        Return queued inspector protocol messages.
        """
    @staticmethod
    def can_dispatch_method(method: builtins.str) -> builtins.bool:
        r"""
        Return whether an inspector protocol method can be dispatched.
        """
    def send(self, message: str | dict[str, object]) -> None:
        r"""
        Send an inspector protocol request or notification.
        """
    def dispatch(self, message: builtins.str) -> None:
        r"""
        Dispatch a raw inspector protocol message.
        """
    def schedule_pause_on_next_statement(self, reason: builtins.str, detail: builtins.str) -> None:
        r"""
        Schedule a debugger pause on the next JavaScript statement.
        """
    def take_messages(self) -> builtins.list[builtins.str]:
        r"""
        Drain and return queued inspector protocol messages.
        """
    def clear_messages(self) -> None:
        r"""
        Clear queued inspector protocol messages.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of queued inspector messages.
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Return whether the session has queued messages.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class Isolate:
    r"""
    Owns one V8 isolate until it is consumed to create a context, builder, or scope.
    """
    def __new__(cls, snapshot: StartupData | bytes | bytearray | memoryview | None = None) -> Isolate:
        r"""
        Create a new V8 isolate, optionally initialized from snapshot startup data.
        """
    def create_context(self) -> Context:
        r"""
        Consume this isolate and create a fresh execution context.
        """
    def create_context_from_snapshot(self, index: builtins.int = 0) -> Context:
        r"""
        Consume this isolate and create a context from a snapshot context index.
        """
    def create_context_builder(self) -> ContextBuilder:
        r"""
        Consume this isolate and return a ContextBuilder for configuring globals and HostAPI.
        """
    def create_scope(self) -> Scope:
        r"""
        Consume this isolate and create a low-level scope for compiling a standalone script.
        """
    def heap_statistics(self) -> dict[str, int | bool]:
        r"""
        Return V8 heap statistics for this isolate.
        """
    def heap_space_statistics(self) -> list[dict[str, int | str]]:
        r"""
        Return per-space V8 heap statistics for this isolate.
        """
    def heap_code_statistics(self) -> dict[str, int]:
        r"""
        Return V8 heap statistics for generated code and metadata.
        """
    def low_memory_notification(self) -> None:
        r"""
        Notify V8 that the host is under low-memory pressure.
        """
    def memory_pressure(self, level: typing.Literal['none', 'moderate', 'critical']) -> None:
        r"""
        Set V8's memory pressure level for this isolate.
        """
    def request_garbage_collection_for_testing(self, collection_type: typing.Literal['full', 'minor'] = "full") -> None:
        r"""
        Request a V8 garbage collection cycle for testing.
        """

@typing.final
class JavaScriptError(builtins.RuntimeError):
    r"""
    Python exception carrying V8 exception, message, and stack metadata.
    """
    @property
    def message(self) -> builtins.str:
        r"""
        Return the exception message.
        """
    @property
    def message_info(self) -> typing.Optional[Message]:
        r"""
        Return structured V8 message metadata when available.
        """
    @property
    def details(self) -> typing.Optional[builtins.str]:
        r"""
        Return V8's formatted message details when available.
        """
    @property
    def source_line(self) -> typing.Optional[builtins.str]:
        r"""
        Return the source line associated with the exception.
        """
    @property
    def script_resource_name(self) -> typing.Optional[builtins.str]:
        r"""
        Return the script resource name associated with the exception.
        """
    @property
    def line_number(self) -> typing.Optional[builtins.int]:
        r"""
        Return the one-based source line number when V8 reports one.
        """
    @property
    def start_column(self) -> builtins.int:
        r"""
        Return the zero-based start column.
        """
    @property
    def end_column(self) -> builtins.int:
        r"""
        Return the zero-based end column.
        """
    @property
    def start_position(self) -> typing.Optional[builtins.int]:
        r"""
        Return the start source position when V8 reports one.
        """
    @property
    def end_position(self) -> typing.Optional[builtins.int]:
        r"""
        Return the end source position when V8 reports one.
        """
    @property
    def wasm_function_index(self) -> typing.Optional[builtins.int]:
        r"""
        Return the WebAssembly function index when the error came from Wasm.
        """
    @property
    def error_level(self) -> builtins.int:
        r"""
        Return V8's message error level.
        """
    @property
    def is_shared_cross_origin(self) -> builtins.bool:
        r"""
        Return whether the message is shared cross-origin.
        """
    @property
    def is_opaque(self) -> builtins.bool:
        r"""
        Return whether the message is opaque.
        """
    @property
    def stack(self) -> typing.Optional[builtins.str]:
        r"""
        Return the formatted JavaScript stack string.
        """
    @property
    def stack_trace(self) -> typing.Optional[StackTrace]:
        r"""
        Return structured stack trace frames when available.
        """
    @property
    def frames(self) -> builtins.list[StackFrame]:
        r"""
        Return stack frames, or an empty list when no stack trace is available.
        """
    def __new__(cls, message: builtins.str) -> JavaScriptError:
        r"""
        Create a JavaScriptError from a message string.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return the formatted exception string.
        """

@typing.final
class Map:
    r"""
    JavaScript Map wrapper.
    """
    @property
    def size(self) -> builtins.int:
        r"""
        Return the number of Map entries.
        """
    def to_value(self) -> Value:
        r"""
        Return this Map as a generic V8 Value.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of Map entries.
        """
    def clear(self) -> None:
        r"""
        Remove all entries from the Map.
        """
    def get(self, key: _JSValueLike) -> Value:
        r"""
        Return the value for a Map key.
        """
    def set(self, key: _JSValueLike, value: _JSValueLike) -> builtins.bool:
        r"""
        Set a Map entry.
        """
    def has(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Return whether the Map contains a key.
        """
    def delete(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Delete a Map entry.
        """
    def __getitem__(self, key: _JSValueLike) -> Value:
        r"""
        Return the value for a Map key.
        """
    def __setitem__(self, key: _JSValueLike, value: _JSValueLike) -> None:
        r"""
        Set a Map entry.
        """
    def __delitem__(self, key: _JSValueLike) -> None:
        r"""
        Delete a Map entry.
        """
    def __contains__(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Return whether the Map contains a key.
        """
    def keys(self) -> list[Value]:
        r"""
        Return Map keys.
        """
    def values(self) -> list[Value]:
        r"""
        Return Map values.
        """
    def items(self) -> list[tuple[Value, Value]]:
        r"""
        Return Map entries as key-value pairs.
        """
    def entries(self) -> list[tuple[Value, Value]]:
        r"""
        Return Map entries as key-value pairs.
        """
    def __iter__(self) -> collections.abc.Iterator[Value]:
        r"""
        Iterate over Map keys.
        """

@typing.final
class Message:
    r"""
    V8 message metadata associated with a JavaScript exception.
    """
    @property
    def text(self) -> builtins.str:
        r"""
        Return V8's message text.
        """
    @property
    def source_line(self) -> typing.Optional[builtins.str]:
        r"""
        Return the source line associated with the message.
        """
    @property
    def script_resource_name(self) -> typing.Optional[builtins.str]:
        r"""
        Return the script resource name associated with the message.
        """
    @property
    def line_number(self) -> typing.Optional[builtins.int]:
        r"""
        Return the one-based source line number when V8 reports one.
        """
    @property
    def start_column(self) -> builtins.int:
        r"""
        Return the zero-based start column.
        """
    @property
    def end_column(self) -> builtins.int:
        r"""
        Return the zero-based end column.
        """
    @property
    def start_position(self) -> typing.Optional[builtins.int]:
        r"""
        Return the start source position when V8 reports one.
        """
    @property
    def end_position(self) -> typing.Optional[builtins.int]:
        r"""
        Return the end source position when V8 reports one.
        """
    @property
    def wasm_function_index(self) -> typing.Optional[builtins.int]:
        r"""
        Return the WebAssembly function index when the message came from Wasm.
        """
    @property
    def error_level(self) -> builtins.int:
        r"""
        Return V8's message error level.
        """
    @property
    def is_shared_cross_origin(self) -> builtins.bool:
        r"""
        Return whether the message is shared cross-origin.
        """
    @property
    def is_opaque(self) -> builtins.bool:
        r"""
        Return whether the message is opaque.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return V8's message text.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class Module:
    r"""
    Compiled ECMAScript module bound to a context.
    """
    @property
    def specifier(self) -> builtins.str:
        r"""
        Return this module's specifier.
        """
    @property
    def status(self) -> builtins.str:
        r"""
        Return V8's current module status name.
        """
    def instantiate(self, imports: _ModuleImportsLike | None = None) -> builtins.bool:
        r"""
        Instantiate this module, optionally resolving imports from a dict.
        """
    def evaluate(self, timeout_ms: typing.Optional[builtins.int] = None) -> Value:
        r"""
        Evaluate this instantiated module and return the completion value.
        """
    def namespace(self) -> Value:
        r"""
        Return the module namespace object.
        """

@typing.final
class Object:
    r"""
    JavaScript Object wrapper.
    """
    @property
    def internal_field_count(self) -> builtins.int:
        r"""
        Return the number of internal fields on this object.
        """
    def to_value(self) -> Value:
        r"""
        Return this object as a generic V8 Value.
        """
    def get(self, key: _JSValueLike) -> Value:
        r"""
        Read an object property.
        """
    def set(self, key: _JSValueLike, value: _JSValueLike) -> builtins.bool:
        r"""
        Set an object property.
        """
    def has(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Return whether this object has a property.
        """
    def delete(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Delete an object property.
        """
    def __getitem__(self, key: _JSValueLike) -> Value:
        r"""
        Read an object property.
        """
    def __setitem__(self, key: _JSValueLike, value: _JSValueLike) -> None:
        r"""
        Set an object property.
        """
    def __delitem__(self, key: _JSValueLike) -> None:
        r"""
        Delete an object property.
        """
    def __contains__(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Return whether this object has a property.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of own property names.
        """
    def keys(self) -> list[object]:
        r"""
        Return this object's own property names.
        """
    def define_own_property(self, key: _JSPropertyNameLike, value: _JSValueLike, attributes: PropertyAttribute | None = None, *, read_only: builtins.bool = False, dont_enum: builtins.bool = False, dont_delete: builtins.bool = False) -> builtins.bool:
        r"""
        Define an own data property with optional V8 attributes.
        """
    def define_property(self, key: _JSPropertyNameLike, descriptor: PropertyDescriptor) -> builtins.bool:
        r"""
        Define a property using a full property descriptor.
        """
    def get_own_property_descriptor(self, key: _JSPropertyNameLike) -> typing.Optional[PropertyDescriptor]:
        r"""
        Return the own property descriptor for a key.
        """
    def get_property_attributes(self, key: _JSValueLike) -> PropertyAttribute:
        r"""
        Return V8 property attributes for a key.
        """
    def set_integrity_level(self, level: builtins.str) -> builtins.bool:
        r"""
        Set this object's integrity level to "sealed" or "frozen".
        """
    def freeze(self) -> builtins.bool:
        r"""
        Freeze this object.
        """
    def seal(self) -> builtins.bool:
        r"""
        Seal this object.
        """
    def get_private(self, key: Private) -> Value:
        r"""
        Read a private property.
        """
    def set_private(self, key: Private, value: _JSValueLike) -> builtins.bool:
        r"""
        Set a private property.
        """
    def has_private(self, key: Private) -> builtins.bool:
        r"""
        Return whether a private property exists.
        """
    def delete_private(self, key: Private) -> builtins.bool:
        r"""
        Delete a private property.
        """
    def get_internal_field(self, index: builtins.int) -> Value | Private | None:
        r"""
        Return an internal field value.
        """
    def set_internal_field(self, index: builtins.int, data: object) -> builtins.bool:
        r"""
        Set an internal field value.
        """

@typing.final
class Private:
    r"""
    V8 Private key wrapper for hidden object properties.
    """
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""
        Return this private key's string name when one exists.
        """
    def name_value(self) -> Value:
        r"""
        Return this private key's V8 name value.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class Promise:
    r"""
    JavaScript Promise wrapper.
    """
    def to_value(self) -> Value:
        r"""
        Return this promise as a generic V8 Value.
        """
    def __await__(self) -> collections.abc.Generator[object, None, Value]:
        r"""
        Await this JavaScript Promise from Python.
        """
    def state(self) -> builtins.str:
        r"""
        Return the promise state.
        """
    def result(self) -> typing.Optional[Value]:
        r"""
        Return the settled promise result, or None while pending.
        """

@typing.final
class PropertyAttribute:
    r"""
    V8 object property attribute bits.
    """
    @property
    def bits(self) -> builtins.int:
        r"""
        Return the raw V8 attribute bits.
        """
    @property
    def read_only(self) -> builtins.bool:
        r"""
        Return whether the property is read-only.
        """
    @property
    def dont_enum(self) -> builtins.bool:
        r"""
        Return whether the property is excluded from enumeration.
        """
    @property
    def dont_delete(self) -> builtins.bool:
        r"""
        Return whether the property cannot be deleted.
        """
    @property
    def writable(self) -> builtins.bool:
        r"""
        Return whether the property is writable.
        """
    @property
    def enumerable(self) -> builtins.bool:
        r"""
        Return whether the property is enumerable.
        """
    @property
    def configurable(self) -> builtins.bool:
        r"""
        Return whether the property is configurable.
        """
    def __new__(cls, *, read_only: builtins.bool = False, dont_enum: builtins.bool = False, dont_delete: builtins.bool = False) -> PropertyAttribute:
        r"""
        Create property attributes from boolean flags.
        """
    @staticmethod
    def none() -> PropertyAttribute:
        r"""
        Return an attribute set with no flags.
        """
    @staticmethod
    def read_only_attribute() -> PropertyAttribute:
        r"""
        Return the read-only attribute.
        """
    @staticmethod
    def dont_enum_attribute() -> PropertyAttribute:
        r"""
        Return the dont-enum attribute.
        """
    @staticmethod
    def dont_delete_attribute() -> PropertyAttribute:
        r"""
        Return the dont-delete attribute.
        """
    def is_none(self) -> builtins.bool:
        r"""
        Return whether no attribute flags are set.
        """
    def __or__(self, other: PropertyAttribute) -> PropertyAttribute:
        r"""
        Combine two attribute sets.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class PropertyDescriptor:
    r"""
    ECMAScript property descriptor used by Object.defineProperty.
    """
    @property
    def value(self) -> _JSValueLike | None:
        r"""
        Return the descriptor value.
        """
    @property
    def get(self) -> _JSAccessorLike | None:
        r"""
        Return the getter function.
        """
    @property
    def set(self) -> _JSAccessorLike | None:
        r"""
        Return the setter function.
        """
    @property
    def writable(self) -> typing.Optional[builtins.bool]:
        r"""
        Return the writable flag.
        """
    @property
    def enumerable(self) -> typing.Optional[builtins.bool]:
        r"""
        Return the enumerable flag.
        """
    @property
    def configurable(self) -> typing.Optional[builtins.bool]:
        r"""
        Return the configurable flag.
        """
    def __new__(cls, value: _JSValueLike | None = None, *, get: _JSAccessorLike | None = None, set: _JSAccessorLike | None = None, writable: typing.Optional[builtins.bool] = None, enumerable: typing.Optional[builtins.bool] = None, configurable: typing.Optional[builtins.bool] = None) -> PropertyDescriptor:
        r"""
        Create a property descriptor.
        """
    @staticmethod
    def data(value: _JSValueLike, *, writable: typing.Optional[builtins.bool] = None, enumerable: typing.Optional[builtins.bool] = None, configurable: typing.Optional[builtins.bool] = None) -> PropertyDescriptor:
        r"""
        Create a data descriptor.
        """
    @staticmethod
    def accessor(*, get: _JSAccessorLike | None = None, set: _JSAccessorLike | None = None, enumerable: typing.Optional[builtins.bool] = None, configurable: typing.Optional[builtins.bool] = None) -> PropertyDescriptor:
        r"""
        Create an accessor descriptor.
        """
    def has_value(self) -> builtins.bool:
        r"""
        Return whether this descriptor has a value field.
        """
    def has_get(self) -> builtins.bool:
        r"""
        Return whether this descriptor has a getter.
        """
    def has_set(self) -> builtins.bool:
        r"""
        Return whether this descriptor has a setter.
        """
    def has_writable(self) -> builtins.bool:
        r"""
        Return whether this descriptor has a writable flag.
        """
    def has_enumerable(self) -> builtins.bool:
        r"""
        Return whether this descriptor has an enumerable flag.
        """
    def has_configurable(self) -> builtins.bool:
        r"""
        Return whether this descriptor has a configurable flag.
        """
    def is_data_descriptor(self) -> builtins.bool:
        r"""
        Return whether this is a data descriptor.
        """
    def is_accessor_descriptor(self) -> builtins.bool:
        r"""
        Return whether this is an accessor descriptor.
        """
    def to_dict(self) -> dict[str, object]:
        r"""
        Convert this descriptor into a Python dict.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class Proxy:
    r"""
    JavaScript Proxy wrapper.
    """
    def to_value(self) -> Value:
        r"""
        Return this Proxy as a generic V8 Value.
        """
    def target(self) -> Value:
        r"""
        Return the proxy target object.
        """
    def handler(self) -> Value:
        r"""
        Return the proxy handler object.
        """
    def is_revoked(self) -> builtins.bool:
        r"""
        Return whether this proxy has been revoked.
        """
    def revoke(self) -> None:
        r"""
        Revoke this proxy when this wrapper owns the revocation capability.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return JavaScript's string representation for this Proxy.
        """

@typing.final
class RegExp:
    r"""
    JavaScript RegExp wrapper.
    """
    @property
    def source(self) -> builtins.str:
        r"""
        Return the RegExp source pattern.
        """
    @property
    def flags(self) -> builtins.str:
        r"""
        Return the RegExp flags.
        """
    def to_value(self) -> Value:
        r"""
        Return this RegExp as a generic V8 Value.
        """
    def exec(self, subject: builtins.str) -> typing.Optional[Object]:
        r"""
        Execute this RegExp against a subject string.
        """
    def test(self, subject: builtins.str) -> builtins.bool:
        r"""
        Return whether this RegExp matches a subject string.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return JavaScript's string representation for this RegExp.
        """

@typing.final
class Scope:
    r"""
    Low-level V8 handle scope used for creating strings and compiling a single script.
    """
    def is_alive(self) -> builtins.bool:
        r"""
        Return whether this scope still owns its isolate.
        """
    def new_string(self, value: builtins.str) -> String:
        r"""
        Create a V8 string in this scope.
        """
    def compile(self, source: String) -> Script:
        r"""
        Compile a string into a script, consuming this scope.
        """

@typing.final
class Script:
    r"""
    Compiled JavaScript script bound to a context.
    """
    @property
    def source(self) -> builtins.str:
        r"""
        Return the source text used to compile this script.
        """
    @property
    def script_id(self) -> builtins.int:
        r"""
        Return V8's script id for this script.
        """
    @property
    def resource_name(self) -> typing.Optional[builtins.str]:
        r"""
        Return the resource name supplied at compile time.
        """
    @property
    def source_map_url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the source map URL supplied at compile time.
        """
    @property
    def source_url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the source URL discovered by V8.
        """
    @property
    def source_mapping_url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the source mapping URL discovered by V8.
        """
    @property
    def cached_data_rejected(self) -> builtins.bool:
        r"""
        Return whether supplied cached data was rejected by V8.
        """
    def run(self, timeout_ms: typing.Optional[builtins.int] = None) -> Value:
        r"""
        Run the compiled script and return its result.
        """
    def create_code_cache(self) -> bytes:
        r"""
        Create V8 code-cache bytes for this script.
        """

@typing.final
class Set:
    r"""
    JavaScript Set wrapper.
    """
    @property
    def size(self) -> builtins.int:
        r"""
        Return the number of Set entries.
        """
    def to_value(self) -> Value:
        r"""
        Return this Set as a generic V8 Value.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of Set entries.
        """
    def clear(self) -> None:
        r"""
        Remove all entries from the Set.
        """
    def add(self, value: _JSValueLike) -> builtins.bool:
        r"""
        Add a value to the Set.
        """
    def has(self, value: _JSValueLike) -> builtins.bool:
        r"""
        Return whether the Set contains a value.
        """
    def delete(self, value: _JSValueLike) -> builtins.bool:
        r"""
        Delete a value from the Set.
        """
    def __contains__(self, value: _JSValueLike) -> builtins.bool:
        r"""
        Return whether the Set contains a value.
        """
    def values(self) -> list[Value]:
        r"""
        Return Set values.
        """
    def keys(self) -> list[Value]:
        r"""
        Return Set values.
        """
    def entries(self) -> list[Value]:
        r"""
        Return Set values in iteration order.
        """
    def __iter__(self) -> collections.abc.Iterator[Value]:
        r"""
        Iterate over Set values.
        """

@typing.final
class SnapshotCreator:
    r"""
    Builder for creating V8 startup snapshots.
    """
    def __new__(cls, existing_snapshot: StartupData | bytes | bytearray | memoryview | None = None) -> SnapshotCreator:
        r"""
        Create a snapshot creator, optionally seeded from existing startup data.
        """
    def is_alive(self) -> builtins.bool:
        r"""
        Return whether this creator can still produce a snapshot.
        """
    def eval(self, source: builtins.str, timeout_ms: typing.Optional[builtins.int] = None) -> None:
        r"""
        Execute JavaScript in the default snapshot context.
        """
    def add_context(self, source: typing.Optional[builtins.str] = None, *, timeout_ms: typing.Optional[builtins.int] = None) -> builtins.int:
        r"""
        Add a context snapshot and return its index.
        """
    def create_blob(self, function_code_handling: typing.Literal['clear', 'keep'] = "clear") -> StartupData:
        r"""
        Finish the snapshot and return startup data.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class StackFrame:
    r"""
    One frame in a JavaScript stack trace.
    """
    @property
    def line(self) -> typing.Optional[builtins.int]:
        r"""
        Return the one-based source line.
        """
    @property
    def line_number(self) -> typing.Optional[builtins.int]:
        r"""
        Return the one-based source line.
        """
    @property
    def column(self) -> typing.Optional[builtins.int]:
        r"""
        Return the zero-based source column.
        """
    @property
    def script_id(self) -> typing.Optional[builtins.int]:
        r"""
        Return V8's script id.
        """
    @property
    def script_name(self) -> typing.Optional[builtins.str]:
        r"""
        Return the script name.
        """
    @property
    def script_name_or_source_url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the script name or source URL.
        """
    @property
    def script_source(self) -> typing.Optional[builtins.str]:
        r"""
        Return the script source when V8 provides it.
        """
    @property
    def script_source_mapping_url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the script source mapping URL.
        """
    @property
    def function_name(self) -> typing.Optional[builtins.str]:
        r"""
        Return the JavaScript function name.
        """
    @property
    def is_eval(self) -> builtins.bool:
        r"""
        Return whether this frame came from eval.
        """
    @property
    def is_constructor(self) -> builtins.bool:
        r"""
        Return whether this frame is a constructor call.
        """
    @property
    def is_wasm(self) -> builtins.bool:
        r"""
        Return whether this frame is WebAssembly.
        """
    @property
    def is_user_javascript(self) -> builtins.bool:
        r"""
        Return whether V8 considers this user JavaScript.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class StackTrace:
    r"""
    Structured JavaScript stack trace.
    """
    @property
    def text(self) -> typing.Optional[builtins.str]:
        r"""
        Return the formatted stack text when V8 provides one.
        """
    @property
    def frames(self) -> builtins.list[StackFrame]:
        r"""
        Return stack frames.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of stack frames.
        """
    def __getitem__(self, index: builtins.int) -> StackFrame:
        r"""
        Return a stack frame by index.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return the formatted stack text, or an empty string.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class StartupData:
    r"""
    Raw V8 startup snapshot data.
    """
    @property
    def byte_length(self) -> builtins.int:
        r"""
        Return the number of bytes in this snapshot.
        """
    def __new__(cls, data: bytes | bytearray | memoryview) -> StartupData:
        r"""
        Wrap snapshot bytes.
        """
    def is_valid(self) -> builtins.bool:
        r"""
        Return whether this snapshot is valid for the linked V8.
        """
    def can_be_rehashed(self) -> builtins.bool:
        r"""
        Return whether V8 can rehash this snapshot for the current build.
        """
    def to_bytes(self) -> bytes:
        r"""
        Return this snapshot as bytes.
        """
    def __bytes__(self) -> bytes:
        r"""
        Return this snapshot as bytes.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the snapshot byte length.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class String:
    r"""
    JavaScript String wrapper.
    """
    @property
    def value(self) -> builtins.str:
        r"""
        Return the string contents.
        """
    def to_value(self) -> Value:
        r"""
        Return this string as a generic V8 Value.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return the string contents.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of Unicode scalar values in this string.
        """

@typing.final
class Symbol:
    r"""
    JavaScript Symbol wrapper.
    """
    def to_value(self) -> Value:
        r"""
        Return this symbol as a generic V8 Value.
        """
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Return this symbol's description.
        """
    def __str__(self) -> builtins.str:
        r"""
        Return JavaScript's string representation for this symbol.
        """

@typing.final
class TypedArray:
    r"""
    JavaScript TypedArray wrapper.
    """
    @property
    def type_name(self) -> builtins.str:
        r"""
        Return the JavaScript typed array constructor name.
        """
    @property
    def length(self) -> builtins.int:
        r"""
        Return the element length.
        """
    @property
    def byte_length(self) -> builtins.int:
        r"""
        Return the byte length.
        """
    @property
    def byte_offset(self) -> builtins.int:
        r"""
        Return the byte offset into the backing ArrayBuffer.
        """
    def to_value(self) -> Value:
        r"""
        Return this TypedArray as a generic V8 Value.
        """
    def buffer(self) -> ArrayBuffer:
        r"""
        Return the backing ArrayBuffer.
        """
    def to_bytes(self) -> bytes:
        r"""
        Copy this TypedArray into Python bytes.
        """
    def copy_contents(self) -> bytes:
        r"""
        Copy this TypedArray into Python bytes.
        """
    def memoryview(self) -> memoryview:
        r"""
        Return a Python memoryview over copied bytes.
        """
    def __bytes__(self) -> bytes:
        r"""
        Return this TypedArray as Python bytes.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the element length.
        """

@typing.final
class Value:
    r"""
    Generic JavaScript value wrapper.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        Return this value's V8 kind name.
        """
    def is_undefined(self) -> builtins.bool:
        r"""
        Return whether this value is JavaScript undefined.
        """
    def is_null(self) -> builtins.bool:
        r"""
        Return whether this value is JavaScript null.
        """
    def is_boolean(self) -> builtins.bool:
        r"""
        Return whether this value is a boolean.
        """
    def is_int32(self) -> builtins.bool:
        r"""
        Return whether this value is an Int32.
        """
    def is_uint32(self) -> builtins.bool:
        r"""
        Return whether this value is a Uint32.
        """
    def is_number(self) -> builtins.bool:
        r"""
        Return whether this value is a JavaScript number.
        """
    def is_big_int(self) -> builtins.bool:
        r"""
        Return whether this value is a BigInt.
        """
    def is_string(self) -> builtins.bool:
        r"""
        Return whether this value is a string.
        """
    def is_symbol(self) -> builtins.bool:
        r"""
        Return whether this value is a symbol.
        """
    def is_array(self) -> builtins.bool:
        r"""
        Return whether this value is an array.
        """
    def is_function(self) -> builtins.bool:
        r"""
        Return whether this value is a function.
        """
    def is_promise(self) -> builtins.bool:
        r"""
        Return whether this value is a Promise.
        """
    def is_map(self) -> builtins.bool:
        r"""
        Return whether this value is a Map.
        """
    def is_set(self) -> builtins.bool:
        r"""
        Return whether this value is a Set.
        """
    def is_date(self) -> builtins.bool:
        r"""
        Return whether this value is a Date.
        """
    def is_regexp(self) -> builtins.bool:
        r"""
        Return whether this value is a RegExp.
        """
    def is_proxy(self) -> builtins.bool:
        r"""
        Return whether this value is a Proxy.
        """
    def is_external(self) -> builtins.bool:
        r"""
        Return whether this value is an External.
        """
    def is_wasm_module(self) -> builtins.bool:
        r"""
        Return whether this value is a WebAssembly.Module object.
        """
    def is_array_buffer(self) -> builtins.bool:
        r"""
        Return whether this value is an ArrayBuffer.
        """
    def is_array_buffer_view(self) -> builtins.bool:
        r"""
        Return whether this value is an ArrayBufferView, TypedArray, or DataView.
        """
    def is_typed_array(self) -> builtins.bool:
        r"""
        Return whether this value is a TypedArray.
        """
    def is_data_view(self) -> builtins.bool:
        r"""
        Return whether this value is a DataView.
        """
    def is_object(self) -> builtins.bool:
        r"""
        Return whether this value is object-like.
        """
    def is_error(self) -> builtins.bool:
        r"""
        Return whether this value is a native JavaScript Error object.
        """
    def is_callable(self) -> builtins.bool:
        r"""
        Return whether this value can be called as a function.
        """
    def typeof(self) -> builtins.str:
        r"""
        Return JavaScript typeof for this value.
        """
    def to_string(self) -> builtins.str:
        r"""
        Convert this value using JavaScript's string conversion.
        """
    def strict_equals(self, other: Value) -> builtins.bool:
        r"""
        Compare this value with JavaScript strict equality.
        """
    def same_value(self, other: Value) -> builtins.bool:
        r"""
        Compare this value with JavaScript SameValue semantics.
        """
    def as_boolean(self) -> typing.Optional[builtins.bool]:
        r"""
        Return this value as bool if it is a JavaScript boolean.
        """
    def as_int32(self) -> typing.Optional[builtins.int]:
        r"""
        Return this value as i32 if it is an Int32.
        """
    def as_uint32(self) -> typing.Optional[builtins.int]:
        r"""
        Return this value as u32 if it is a Uint32.
        """
    def as_number(self) -> typing.Optional[builtins.float]:
        r"""
        Return this value as f64 if it is a JavaScript number.
        """
    def as_big_int(self) -> int | None:
        r"""
        Return this value as a Python int if it is a BigInt.
        """
    def as_big_int_i64(self) -> typing.Optional[builtins.int]:
        r"""
        Return this BigInt as i64 when the conversion is lossless.
        """
    def as_big_int_string(self) -> typing.Optional[builtins.str]:
        r"""
        Return this BigInt as a decimal string.
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Return JavaScript truthiness for this value.
        """
    def __int__(self) -> int:
        r"""
        Convert this numeric or BigInt value to a Python int.
        """
    def __float__(self) -> builtins.float:
        r"""
        Convert this numeric value to a Python float.
        """
    def as_array(self) -> list[object] | None:
        r"""
        Convert this array value to a Python object.
        """
    def as_object(self) -> dict[object, object] | None:
        r"""
        Convert this object value to a Python object.
        """
    def as_function(self) -> dict[str, str] | None:
        r"""
        Convert this function value to a Python object.
        """
    def as_v8_string(self) -> typing.Optional[String]:
        r"""
        Return this value as a String wrapper.
        """
    def as_v8_object(self) -> typing.Optional[Object]:
        r"""
        Return this value as an Object wrapper.
        """
    def as_v8_array(self) -> typing.Optional[Array]:
        r"""
        Return this value as an Array wrapper.
        """
    def as_v8_function(self) -> typing.Optional[Function]:
        r"""
        Return this value as a Function wrapper.
        """
    def as_v8_promise(self) -> typing.Optional[Promise]:
        r"""
        Return this value as a Promise wrapper.
        """
    def as_v8_map(self) -> typing.Optional[Map]:
        r"""
        Return this value as a Map wrapper.
        """
    def as_map(self) -> typing.Optional[Map]:
        r"""
        Return this value as a Map wrapper.
        """
    def as_v8_set(self) -> typing.Optional[Set]:
        r"""
        Return this value as a Set wrapper.
        """
    def as_set(self) -> typing.Optional[Set]:
        r"""
        Return this value as a Set wrapper.
        """
    def as_v8_date(self) -> typing.Optional[Date]:
        r"""
        Return this value as a Date wrapper.
        """
    def as_date(self) -> typing.Optional[Date]:
        r"""
        Return this value as a Date wrapper.
        """
    def as_v8_regexp(self) -> typing.Optional[RegExp]:
        r"""
        Return this value as a RegExp wrapper.
        """
    def as_regexp(self) -> typing.Optional[RegExp]:
        r"""
        Return this value as a RegExp wrapper.
        """
    def as_v8_proxy(self) -> typing.Optional[Proxy]:
        r"""
        Return this value as a Proxy wrapper.
        """
    def as_proxy(self) -> typing.Optional[Proxy]:
        r"""
        Return this value as a Proxy wrapper.
        """
    def as_v8_external(self) -> typing.Optional[External]:
        r"""
        Return this value as an External wrapper.
        """
    def as_external(self) -> typing.Optional[External]:
        r"""
        Return this value as an External wrapper.
        """
    def as_v8_wasm_module(self) -> typing.Optional[WasmModule]:
        r"""
        Return this value as a WasmModule wrapper.
        """
    def as_wasm_module(self) -> typing.Optional[WasmModule]:
        r"""
        Return this value as a WasmModule wrapper.
        """
    def as_v8_big_int(self) -> typing.Optional[BigInt]:
        r"""
        Return this value as a BigInt wrapper.
        """
    def as_v8_symbol(self) -> typing.Optional[Symbol]:
        r"""
        Return this value as a Symbol wrapper.
        """
    def as_v8_array_buffer(self) -> typing.Optional[ArrayBuffer]:
        r"""
        Return this value as an ArrayBuffer wrapper.
        """
    def as_v8_array_buffer_view(self) -> typing.Optional[ArrayBufferView]:
        r"""
        Return this value as an ArrayBufferView wrapper.
        """
    def as_v8_typed_array(self) -> typing.Optional[TypedArray]:
        r"""
        Return this value as a TypedArray wrapper.
        """
    def as_v8_data_view(self) -> typing.Optional[DataView]:
        r"""
        Return this value as a DataView wrapper.
        """
    def get(self, key: _JSValueLike) -> Value:
        r"""
        Read an object property after converting this value to an object.
        """
    def get_index(self, index: builtins.int) -> Value:
        r"""
        Read an indexed object property.
        """
    def set(self, key: _JSValueLike, value: _JSValueLike) -> builtins.bool:
        r"""
        Set an object property after converting this value to an object.
        """
    def set_index(self, index: builtins.int, value: _JSValueLike) -> builtins.bool:
        r"""
        Set an indexed object property.
        """
    def has(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Return whether this value's object form has a property.
        """
    def delete(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Delete an object property after converting this value to an object.
        """
    def __getitem__(self, key: _JSValueLike) -> Value:
        r"""
        Read an object property.
        """
    def __setitem__(self, key: _JSValueLike, value: _JSValueLike) -> None:
        r"""
        Set an object property.
        """
    def __delitem__(self, key: _JSValueLike) -> None:
        r"""
        Delete an object property.
        """
    def __contains__(self, key: _JSValueLike) -> builtins.bool:
        r"""
        Return whether this value's object form has a property.
        """
    def keys(self) -> list[object]:
        r"""
        Return this object's own property names.
        """
    def define_own_property(self, key: _JSPropertyNameLike, value: _JSValueLike, attributes: PropertyAttribute | None = None, *, read_only: builtins.bool = False, dont_enum: builtins.bool = False, dont_delete: builtins.bool = False) -> builtins.bool:
        r"""
        Define an own data property with optional V8 attributes.
        """
    def define_property(self, key: _JSPropertyNameLike, descriptor: PropertyDescriptor) -> builtins.bool:
        r"""
        Define a property using a full property descriptor.
        """
    def get_own_property_descriptor(self, key: _JSPropertyNameLike) -> typing.Optional[PropertyDescriptor]:
        r"""
        Return the own property descriptor for a key.
        """
    def get_property_attributes(self, key: _JSValueLike) -> PropertyAttribute:
        r"""
        Return V8 property attributes for a key.
        """
    def set_integrity_level(self, level: builtins.str) -> builtins.bool:
        r"""
        Set this object's integrity level to "sealed" or "frozen".
        """
    def freeze(self) -> builtins.bool:
        r"""
        Freeze this object value.
        """
    def seal(self) -> builtins.bool:
        r"""
        Seal this object value.
        """
    def get_private(self, key: Private) -> Value:
        r"""
        Read a private property.
        """
    def set_private(self, key: Private, value: _JSValueLike) -> builtins.bool:
        r"""
        Set a private property.
        """
    def has_private(self, key: Private) -> builtins.bool:
        r"""
        Return whether a private property exists.
        """
    def delete_private(self, key: Private) -> builtins.bool:
        r"""
        Delete a private property.
        """
    def internal_field_count(self) -> builtins.int:
        r"""
        Return the number of internal fields on this value's object form.
        """
    def get_internal_field(self, index: builtins.int) -> Value | Private | None:
        r"""
        Return an internal field value.
        """
    def set_internal_field(self, index: builtins.int, data: object) -> builtins.bool:
        r"""
        Set an internal field value.
        """
    def length(self) -> typing.Optional[builtins.int]:
        r"""
        Return this value's natural length when it has one.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return this value's natural length.
        """
    def instance_of(self, constructor: Value) -> builtins.bool:
        r"""
        Evaluate JavaScript instanceof against a constructor value.
        """
    def __pos__(self) -> Value:
        r"""
        Apply JavaScript unary plus.
        """
    def __neg__(self) -> Value:
        r"""
        Apply JavaScript unary negation.
        """
    def __invert__(self) -> Value:
        r"""
        Apply JavaScript bitwise not.
        """
    def __add__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript addition.
        """
    def __radd__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected addition.
        """
    def __sub__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript subtraction.
        """
    def __rsub__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected subtraction.
        """
    def __mul__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript multiplication.
        """
    def __rmul__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected multiplication.
        """
    def __truediv__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript division.
        """
    def __rtruediv__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected division.
        """
    def __mod__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript remainder.
        """
    def __rmod__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected remainder.
        """
    def __pow__(self, exponent: _JSValueLike, modulo: None = None) -> Value:
        r"""
        Apply JavaScript exponentiation.
        """
    def __rpow__(self, base: _JSValueLike, modulo: None = None) -> Value:
        r"""
        Apply JavaScript reflected exponentiation.
        """
    def __and__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript bitwise and.
        """
    def __rand__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected bitwise and.
        """
    def __or__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript bitwise or.
        """
    def __ror__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected bitwise or.
        """
    def __xor__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript bitwise xor.
        """
    def __rxor__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected bitwise xor.
        """
    def __lshift__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript left shift.
        """
    def __rlshift__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected left shift.
        """
    def __rshift__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript right shift.
        """
    def __rrshift__(self, other: _JSValueLike) -> Value:
        r"""
        Apply JavaScript reflected right shift.
        """
    def __eq__(self, other: _JSValueLike) -> builtins.bool:
        r"""
        Apply JavaScript loose equality.
        """
    def __ne__(self, other: _JSValueLike) -> builtins.bool:
        r"""
        Apply JavaScript loose inequality.
        """
    def __lt__(self, other: _JSValueLike) -> builtins.bool:
        r"""
        Apply JavaScript less-than comparison.
        """
    def __le__(self, other: _JSValueLike) -> builtins.bool:
        r"""
        Apply JavaScript less-than-or-equal comparison.
        """
    def __gt__(self, other: _JSValueLike) -> builtins.bool:
        r"""
        Apply JavaScript greater-than comparison.
        """
    def __ge__(self, other: _JSValueLike) -> builtins.bool:
        r"""
        Apply JavaScript greater-than-or-equal comparison.
        """
    def promise_state(self) -> typing.Optional[builtins.str]:
        r"""
        Return the promise state when this value is a Promise.
        """
    def promise_result(self) -> typing.Optional[Value]:
        r"""
        Return the settled promise result, or None when pending or not a Promise.
        """
    def __await__(self) -> collections.abc.Generator[object, None, Value]:
        r"""
        Await this value when it is a JavaScript Promise.
        """
    def call(self, args: _JSFunctionArgsLike | None = None, this_arg: _JSValueLike | None = None) -> Value:
        r"""
        Call this value when it is a JavaScript function.
        """
    def __call__(self, *args: _JSValueLike) -> Value:
        r"""
        Call this value with positional arguments.
        """
    def to_python(self) -> object:
        r"""
        Convert this JavaScript value to a Python object.
        """
    def to_json(self) -> typing.Optional[builtins.str]:
        r"""
        Serialize this value with JSON.stringify.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Convert this value using JavaScript's string conversion.
        """

@typing.final
class WasmModule:
    r"""
    JavaScript WebAssembly.Module object wrapper.
    """
    @property
    def wire_bytes(self) -> bytes:
        r"""
        Return this module's wire bytes.
        """
    @property
    def source_url(self) -> builtins.str:
        r"""
        Return this module's source URL metadata.
        """
    def to_value(self) -> Value:
        r"""
        Return this module as a generic V8 Value.
        """
    def get_compiled_module(self) -> CompiledWasmModule:
        r"""
        Return the reusable compiled module handle.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

@typing.final
class WasmModuleCache:
    r"""
    Cache of compiled WebAssembly modules keyed by their wire bytes.
    """
    @property
    def hits(self) -> builtins.int:
        r"""
        Return the number of cache hits.
        """
    @property
    def misses(self) -> builtins.int:
        r"""
        Return the number of cache misses.
        """
    @property
    def stores(self) -> builtins.int:
        r"""
        Return the number of modules stored in the cache.
        """
    def __new__(cls) -> WasmModuleCache:
        r"""
        Create an empty WebAssembly module cache.
        """
    def clear(self) -> None:
        r"""
        Remove all cached modules while keeping hit and miss counters.
        """
    def contains(self, wire_bytes: bytes | bytearray | memoryview) -> builtins.bool:
        r"""
        Return whether the cache contains a module for the given wire bytes.
        """
    def insert(self, module: WasmModule) -> None:
        r"""
        Insert a compiled module from an existing WasmModule object.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of cached modules.
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Return whether this cache contains any modules.
        """
    def __contains__(self, wire_bytes: object) -> builtins.bool:
        r"""
        Return whether the cache contains a module for the given bytes-like key.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a debug representation.
        """

def _gc_callback(phase: builtins.str, _info: object) -> None:
    r"""
    Internal callback installed into Python's gc module to release retired V8 isolates.
    """

def cached_data_version_tag() -> builtins.int:
    r"""
    Return V8's cached-data version tag for script code cache compatibility checks.
    """

def collect_garbage() -> builtins.int:
    r"""
    Run Python's gc.collect(), then release pending V8 isolates in safe reverse creation order.
    """

